// Generated by tools/gen-vehicle-marking-seats.mjs.
// First-party procedural vehicle artwork and engineering: Kevin Liu.

export const VEHICLE_MARKING_SEAT_SCHEMA_VERSION = 1;

import type { VehicleMarkingSeatRecord } from '../vehicleMarkingSeatRegistry.ts';

export const VEHICLE_MARKING_SEATS: Readonly<Record<string, VehicleMarkingSeatRecord>> = Object.freeze({
  "m1a1_x": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "insignia",
        "parent": "turret",
        "size": 0.24,
        "pos": [
          -1.4120679,
          0.5869951,
          -1.4751641
        ],
        "quaternion": [
          -0.1859842,
          -0.6822096,
          -0.1859842,
          0.6822096
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "m1a1_x",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0
      },
      {
        "kind": "designation",
        "parent": "turret",
        "size": 0.24,
        "pos": [
          -1.4120679,
          0.5869951,
          -0.9462035
        ],
        "quaternion": [
          -0.1859842,
          -0.6822096,
          -0.1859842,
          0.6822096
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "m1a1_x",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0
      }
    ]
  },
  "m1a1ha_x": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "insignia",
        "parent": "turret",
        "size": 0.24,
        "pos": [
          -1.4120679,
          0.5869951,
          -1.4751641
        ],
        "quaternion": [
          -0.1859842,
          -0.6822096,
          -0.1859842,
          0.6822096
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "m1a1ha_x",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0
      },
      {
        "kind": "designation",
        "parent": "turret",
        "size": 0.24,
        "pos": [
          -1.4120679,
          0.5869951,
          -0.9462035
        ],
        "quaternion": [
          -0.1859842,
          -0.6822096,
          -0.1859842,
          0.6822096
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "m1a1ha_x",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0
      }
    ]
  },
  "m1a2_x": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "insignia",
        "parent": "turret",
        "size": 0.24,
        "pos": [
          -1.4120679,
          0.5869951,
          -1.4751641
        ],
        "quaternion": [
          -0.1859842,
          -0.6822096,
          -0.1859842,
          0.6822096
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "m1a2_x",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0
      },
      {
        "kind": "designation",
        "parent": "turret",
        "size": 0.24,
        "pos": [
          -1.4120679,
          0.5869951,
          -0.9462035
        ],
        "quaternion": [
          -0.1859842,
          -0.6822096,
          -0.1859842,
          0.6822096
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "m1a2_x",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0
      }
    ]
  },
  "m1a2_tusk_x": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "insignia",
        "parent": "turret",
        "size": 0.24,
        "pos": [
          1.2190416,
          0.6836303,
          -0.8981162
        ],
        "quaternion": [
          -0.1859946,
          0.6822067,
          0.1859946,
          0.6822067
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "m1a2_tusk_x",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0
      },
      {
        "kind": "designation",
        "parent": "turret",
        "size": 0.24,
        "pos": [
          1.2190416,
          0.6836303,
          -0.3691556
        ],
        "quaternion": [
          -0.1859946,
          0.6822067,
          0.1859946,
          0.6822067
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "m1a2_tusk_x",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0
      }
    ]
  },
  "m1a2_sepv2_x": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "insignia",
        "parent": "turret",
        "size": 0.24,
        "pos": [
          1.2190416,
          0.6836303,
          -0.8981162
        ],
        "quaternion": [
          -0.1859946,
          0.6822067,
          0.1859946,
          0.6822067
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "m1a2_sepv2_x",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0
      },
      {
        "kind": "designation",
        "parent": "turret",
        "size": 0.24,
        "pos": [
          1.2190416,
          0.6836303,
          -0.3691556
        ],
        "quaternion": [
          -0.1859946,
          0.6822067,
          0.1859946,
          0.6822067
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "m1a2_sepv2_x",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0
      }
    ]
  },
  "m1a2_sepv3_x": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "insignia",
        "parent": "turret",
        "size": 0.24,
        "pos": [
          -1.4120679,
          0.5869951,
          -1.4751641
        ],
        "quaternion": [
          -0.1859842,
          -0.6822096,
          -0.1859842,
          0.6822096
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "m1a2_sepv3_x",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0
      },
      {
        "kind": "designation",
        "parent": "turret",
        "size": 0.24,
        "pos": [
          -1.4120679,
          0.5869951,
          -0.9462035
        ],
        "quaternion": [
          -0.1859842,
          -0.6822096,
          -0.1859842,
          0.6822096
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "m1a2_sepv3_x",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0
      }
    ]
  },
  "ua_m1a1_x": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "insignia",
        "parent": "turret",
        "size": 0.24,
        "pos": [
          -1.4120679,
          0.5869951,
          -1.4751641
        ],
        "quaternion": [
          -0.1859842,
          -0.6822096,
          -0.1859842,
          0.6822096
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "ua_m1a1_x",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0
      },
      {
        "kind": "designation",
        "parent": "turret",
        "size": 0.24,
        "pos": [
          -1.4120679,
          0.5869951,
          -0.9462035
        ],
        "quaternion": [
          -0.1859842,
          -0.6822096,
          -0.1859842,
          0.6822096
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "ua_m1a1_x",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0
      }
    ]
  }
});
